### ISSUE TITLE
Compilation error: libmate-desktop/mate-rr.h not found

### ISSUE THREAD

**Issue by Lutwick** [NiceandGently/mate-color-manager#8]
Hi,

I'm trying to install mate-color-manager in Linux Mint 13, based on Ubuntu 12.04 (precise). Via backport updates I have MATE 1.6.

autogen.sh seems to complete successfully (see below), but when I run make, I finally get the error message:

Making all in src
make[2]: Entering directory '/home/ludwick/mate-color-manager-master/src'
CC     libmcmshared_a-mcm-screen.o
In file included from mcm-screen.c:37:0:
mcm-screen.h:27:37: fatal error: libmate-desktop/mate-rr.h: No such file or directory
compilation terminated.
make[2]: *** [libmcmshared_a-mcm-screen.o] Error 1
make[2]: Leaving directory '/home/ludwick/Desktop/mate-color-manager-master/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ludwick/Desktop/mate-color-manager-master'
make: *** [all] Error 2

I located mate-rr.h in
./usr/include/mate-desktop-2.0/libmateui/mate-rr.h

Any idea how I can make the compiler find it there?

Not sure if that has anything to do with it, but I could not find the package you mention in your dependency list
liblcms-dev
Only liblcms1-dev and liblcms2-dev, which I installed.

Thanks!

Output of ./autogen.sh

/usr/bin/mate-autogen
/usr/bin/yelp-build
checking for autoconf >= 2.53...
  testing autoconf2.50... not found.
  testing autoconf... found 2.68
checking for automake >= 1.9...
  testing automake-1.14... not found.
  testing automake-1.13... not found.
  testing automake-1.12... not found.
  testing automake-1.11... found 1.11.3
checking for libtool >= 1.4.3...
  testing libtoolize... found 2.4.2
checking for glib-gettext >= 2.2.0...
  testing glib-gettextize... found 2.32.4
checking for intltool >= 0.25...
  testing intltoolize... found 0.50.2
checking for pkg-config >= 0.14.0...
  testing pkg-config... found 0.26
checking for gtk-doc >= 1.0...
  testing gtkdocize... found 1.18
Checking for required M4 macros...
Checking for forbidden M4 macros...
Processing ./configure.ac
Running libtoolize...
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
Running glib-gettextize... Ignore non-fatal messages.
Copying file mkinstalldirs
Copying file po/Makefile.in.in

Please add the files
  codeset.m4 gettext.m4 glibc21.m4 iconv.m4 isc-posix.m4 lcmessage.m4
  progtest.m4
from the /aclocal directory to your autoconf macro directory
or directly to your aclocal.m4 file.
You will also need config.guess and config.sub, which you can get from
ftp://ftp.gnu.org/pub/gnu/config/.

Running intltoolize...
Running gtkdocize...
Running aclocal-1.11...
Running autoconf...
Running autoheader...
Running automake-1.11...
Running ./configure ...
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert i686-pc-linux-gnu file names to i686-pc-linux-gnu format... func_convert_file_noop
checking how to convert i686-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether gcc and cc understand -c and -o together... yes
checking whether NLS is requested... yes
checking for intltool >= 0.35.0... 0.50.2 found
checking for intltool-update... /usr/bin/intltool-update
checking for intltool-merge... /usr/bin/intltool-merge
checking for intltool-extract... /usr/bin/intltool-extract
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for perl... /usr/bin/perl
checking for perl >= 5.8.1... 5.14.2
checking for XML::Parser... ok
checking what warning flags to pass to the C compiler... -Wall -Wmissing-prototypes
checking what language compliance flags to pass to the C compiler... 
checking for itstool... itstool
checking for xmllint... xmllint
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for gtkdoc-check... /usr/bin/gtkdoc-check
checking for gtkdoc-rebase... /usr/bin/gtkdoc-rebase
checking for gtkdoc-mkpdf... /usr/bin/gtkdoc-mkpdf
checking whether to build gtk-doc documentation... no
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking for LC_MESSAGES... yes
checking libintl.h usability... yes
checking libintl.h presence... yes
checking for libintl.h... yes
checking for ngettext in libc... yes
checking for dgettext in libc... yes
checking for bind_textdomain_codeset... yes
checking for msgfmt... (cached) /usr/bin/msgfmt
checking for dcgettext... yes
checking if msgfmt accepts -c... yes
checking for gmsgfmt... (cached) /usr/bin/msgfmt
checking for xgettext... (cached) /usr/bin/xgettext
checking for pkg-config... (cached) /usr/bin/pkg-config
checking pkg-config is at least version 0.16... yes
checking for GLIB... yes
checking for XORG... yes
checking for GTK... yes
checking for MATEDESKTOP... yes
checking for UNIQUE... yes
checking for VTE... yes
checking for GUDEV... yes
checking for LCMS... yes
checking for X11... yes
checking for NOTIFY... yes
checking for SANE... yes
checking for EXIV... yes
checking for CANBERRA... yes
checking for EXIF... yes
checking for TIFFReadRGBAImageOriented in -ltiff... yes
checking cups/cups.h usability... yes
checking cups/cups.h presence... yes
checking for cups/cups.h... yes
checking for cupsGetDefault in -lcups... yes
checking for docbook2man... no
configure: creating ./config.status
config.status: creating Makefile
config.status: creating data/Makefile
config.status: creating data/icons/Makefile
config.status: creating data/icons/16x16/Makefile
config.status: creating data/icons/22x22/Makefile
config.status: creating data/icons/24x24/Makefile
config.status: creating data/icons/32x32/Makefile
config.status: creating data/icons/48x48/Makefile
config.status: creating data/icons/64x64/Makefile
config.status: creating data/icons/256x256/Makefile
config.status: creating data/icons/scalable/Makefile
config.status: creating data/tests/Makefile
config.status: creating data/targets/Makefile
config.status: creating data/figures/Makefile
config.status: creating help/Makefile
config.status: creating man/Makefile
config.status: creating policy/Makefile
config.status: creating po/Makefile.in
config.status: creating rules/Makefile
config.status: creating src/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing default-1 commands
config.status: executing po/stamp-it commands

                    mate-color-manager 1.8.0
                  ================================

        prefix:                    /usr/local
        datadir:                   ${datarootdir}
        compiler:                  gcc
        cflags:                    -g -O2
        cppflags:                  
        PackageKit integration:    yes
        SANE support:              yes
        RAW support:               yes
        building unit tests:       yes

Now type 'make' to compile mate-color-manager

**Comment by NiceandGently** [comment]
Reason for that issue is that libmate is obsolete with mate-1.8.x and some file are moved to mate-desktop with different paths.
For m-c-m i followed that change with https://github.com/NiceandGently/mate-color-manager/commit/9bd2468c9f60a0967834e64ec668c2fadfc244b5
You can sove your issue with reverting this commit (exept help changes in src/mcm-utils.c),
or use m-c-m-1.6.1 tarball for mate-1.6.x.

**Comment by Lutwick** [comment]
Thanks for the quick reply! I only tried the current master and 1.7.0.
I should just have tried 1.6.1 as well, because it compiled and installed without any problems!

Unfortunately I realised, that gnome-color-manager does not really provide the feature I was looking for. I just want a tool, by which I can alter the RGB intensity of my screen.
(like this guy: http://askubuntu.com/questions/424732/how-do-i-calibrate-colors-without-extra-hardware-like-dccw-exe-on-windows)

Is there anything like that for MATE?

Thanks and all the best!

**Comment by NiceandGently** [comment]
Honestly, i forked m-c-m in the early days of mate for a fedora user who is a photograph.
I do my best from the code side but i never use it for myself :/
In result i don't know very much about using it, and i recommend to ask in mate forum for help or send a PM to user 'megaloman'.
